### ISSUE TITLE
Add a Readme.md

### ISSUE THREAD

**Issue by JesuFemi-O** [Victor-Akinode/projects-assessments#1]
Hey @Victor-Akinode this is an empty repository. Kindly add a readme.md file to your main branch and close this issue once you've done that.

[Here's](https://www.youtube.com/watch?v=a8CwpGARAsQ&pp=ygUaZ2l0aHViIHJlYWRtZS5tZCB0ZW1wbGF0ZSA%3D) a video on how to create effective readme files incase you'll like to watch one

**Comment by Victor-Akinode** [comment]
This is corrected now. Thank you. Please help check, @JesuFemi-O  to know if the right thing was done.
I updated the READme.md file to the extent at which I have worked. I will keep updating as I proceed.
